name : 01 Workflow Events
on : push
jobs : 
    echo:
        runs-on : ubuntu-latest
        steps : 
            -   name : Show the Triggers
                run : echo "this is aa(n) ${{ github.event_name }} event." 